export const OPEN_LOGIN_MODAL = 'OPEN_LOGIN_MODAL';
export const OPEN_REGISTER_MODAL = 'OPEN_REGISTER_MODAL';
export const CLOSE_MODAL = 'CLOSE_MODAL';

export const REGISTER_USER_REQUEST = 'REGISTER_USER_REQUEST';
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const REGISTER_USER_FAILURE = 'REGISTER_USER_FAILURE';

export const GET_TOKEN_REQUEST = 'GET_TOKEN_REQUEST';
export const GET_TOKEN_SUCCESS = 'GET_TOKEN_SUCCESS';
export const GET_TOKEN_FAILURE = 'GET_TOKEN_FAILURE';

export const LOG_IN_REQUEST = 'LOG_IN_REQUEST';
export const LOG_IN_SUCCESS = 'LOG_IN_SUCCESS';
export const LOG_IN_FAILURE = 'LOG_IN_FAILURE';
export const LOG_OUT = 'LOG_OUT';

export const SEND_MESSAGE = 'SEND_MESSAGE';
export const NEW_MESSAGE = 'NEW_MESSAGE';

export const UPDATE_GAMES = 'UPDATE_GAMES';
export const CREATE_GAME_REQUEST = 'CREATE_GAME_REQUEST';
export const CREATE_GAME_SUCCESS = 'CREATE_GAME_SUCCESS';
export const GAME_CREATED = 'GAME_CREATED';

export const JOIN_GAME_REQUEST = 'JOIN_GAME_REQUEST';
export const JOIN_GAME_SUCCESS = 'JOIN_GAME_SUCCESS';
export const JOIN_GAME_FAILURE = 'JOIN_GAME_FAILURE';
export const PLAYER_JOINED = 'PLAYER_JOINED';

export const LEAVE_GAME_REQUEST = 'LEAVE_GAME_REQUEST';
export const LEAVE_GAME_SUCCESS = 'LEAVE_GAME_SUCCESS';
export const PLAYER_LEFT = 'PLAYER_LEFT';

export const SEND_GAME_MESSAGE = 'SEND_GAME_MESSAGE';
export const NEW_GAME_MESSAGE = 'NEW_GAME_MESSAGE';

export const PLAYER_RECONNECTED = 'PLAYER_RECONNECTED';
export const PLAYER_DISCONNECTED = 'PLAYER_DISCONNECTED';

export const START_GAME_REQUEST = 'START_GAME_REQUEST';
export const START_GAME_SUCCESS = 'START_GAME_SUCCESS';
export const GAME_STARTED = 'GAME_STARTED';

export const UPDATE_GAME_STATE = 'UPDATE_GAME_STATE';
export const PERFORM_GAME_ACTION = 'PERFORM_GAME_ACTION';
export const CLOSE_GAME_MODAL = 'CLOSE_GAME_MODAL';
