export const EMAIL_TAKEN = 'EMAIL_TAKEN';
export const USERNAME_TAKEN = 'USERNAME_TAKEN';
export const PASSWORDS_DO_NOT_MATCH = 'PASSWORDS_DO_NOT_MATCH';

export const AUTHENTICATION_FAILURE = 'AUTHENTICATION_FAILURE';
